### PR TITLE
Lock dependency versions

### PR DESCRIPTION
**Pull request by richardnuno**
An issue with the most recent bundler (1.10.x) was causing an issue whereby the dependencies weren’t being resolved.

### CODE REVIEW

**Comment by athal7** [comment]
:+1: assuming tests can pass

**Comment by richardnuno** [comment]
still seems to be failing, will keep looking into it

**Comment by richardnuno** [comment]
@athal7 `sass-rails` was causing the dependencies to not be resolved for some reason (not sure why). Besides locking down the gem versions I've removed `sass-rails` since we don't use sass anywhere in this extension. CI is green now, mind taking another look?

**Comment by athal7** [comment]
i'm curious how the other extensions do not require version lockdowns. but if it is necessary then :+1:

**Comment by richardnuno** [comment]
If you take a look at [multi-domain] (https://github.com/bonobos/spree-multi-domain/blob/2-2-dev/spree_multi_domain.gemspec) many of them are locked down. That one in particular doesn't have `sass-rails` so that's why I'm assuming it recently passed but can't be sure. This extension started failing in CI since the release of bundler 1.10.x so I think it's mostly a bundler issue.

**Comment by athal7** [comment]
cool thanks for the explanation. :ship: :it:

**Pull request merged**
