### PR TITLE
Add stock location name to the return_item serializer

### PR DESCRIPTION
**Pull request by richardnuno**

### CODE REVIEW

**Comment by athal7** [comment]
do we want to include the warehouse identifier as well?

**Comment by athal7** [comment]
:+1:

**Comment by richardnuno** [comment]
Changed it to `stock_location_code`, it's still looking at the stock location's name for now. @athal7 mind taking a second look?

**Comment by athal7** [comment]
:shipit:

**Comment by richardnuno** [comment]
@athal7 forgot the version bump

**Comment by athal7** [comment]
:+1:

**Pull request merged**
