### PR TITLE
Make the stock transfer creation transactional

### PR DESCRIPTION
**Pull request by richardnuno**
Also lock the bundler version at 1.9.9 because 1.10.x was causing issues.

### CODE REVIEW

**Comment by athal7** [comment]
:+1:

**Comment by richardnuno** [comment]
Rebased on top of current 2-2-dev, should fix the tests

**Comment by richardnuno** [comment]
blocked by https://github.com/bonobos/spree/pull/396

**Comment by richardnuno** [comment]
Rebased and updated version. Merging since https://github.com/bonobos/spree/pull/396 has been merged and tests pass locally.

**Pull request merged**
