### PR TITLE
Stub Cancellation Mailer in spec

### PR DESCRIPTION
**Pull request by allisonlarson**
Fix a spec where cancellation mailer was getting called and throwing an
error.

### CODE REVIEW

**Comment by allisonlarson** [comment]
I couldn't figure out why this was failing here, but figured that stubbing out the mailer was fine since it wasn't what was being tested specifically.

**Comment by richardnuno** [comment]
Looks good to me :+1: We just need to remember to bump the versions on the other PR's after this one's merged

**Comment by athal7** [comment]
what about disabling actionmailer in test entirely instead of this specific mailer?

**Comment by athal7** [comment]
hm it seems maybe that is already happening.

**Comment by allisonlarson** [comment]
It doesn't actually mail anything in test, it accumulates in ActionMailer::Base.deliveries array. So, I don't know. Figured that would be unexpected?

**Comment by allisonlarson** [comment]
@athal7 is this cool with you?

**Comment by athal7** [comment]
i guess i'm just confused why this is necessary, but i trust that it is :+1:

**Pull request merged**
