### PR TITLE
add order_id to refund serializer

### PR DESCRIPTION
**Pull request by allisonlarson**

### CODE REVIEW

**Comment by athal7** [comment]
i think the order number would be more useful than the db id. simparel uses that for reference more frequently

**Comment by allisonlarson** [comment]
Good catch; it's supposed to be the order number. Simparel refers to it as the id, which is where I mixed them up.

**Comment by allisonlarson** [comment]
https://github.com/bonobos/simparel_api/pull/64
https://github.com/wombat/simparel_integration/pull/25
https://github.com/bonobos/spree-backend/pull/947

**Comment by athal7** [comment]
:+1:

**Pull request merged**
